### ISSUE TITLE
Issue with running MySQL server on Win 7

### ISSUE THREAD

**Issue by shubhamkr1** [airavata-courses/sachinkariyattin#3]
I have installed MySQL Server 5.7, Workbench 6.3, MySQL Router, Shell and utilities on Win 7 in my C drive. When I start Workbench and try to 'open connection' for my local instance of mysql router, the connection fails.

Error - Could not connect, server may not be running.	Can't connect to MySQL server on 'localhost' (10061)

Mysql router is running. when I try to run Mysql service from Services tool, it fails. I have tried the following steps -
Ran "C:\Program Files\MySQL\MySQL Server 5.5\bin\mysqld" --install from the command line to add it to my services, ran services.msc (start -> run), found the MySQL service and started it.

But still I get same error on workbench. this could be an issue with my system, but I cannot figure it out.

**Comment by sachinkariyattin** [comment]
@shubhamkr1 
You should be able to install MySQL very easily on windows. May be the issue could be something related to your system as you mentioned. You could try a fresh install of MySQL and try it again OR you could try running it on a different machine may be.
