### ISSUE TITLE
All Services not Starting

### ISSUE THREAD

**Issue by hiteshkumardasika** [airavata-courses/sachinkariyattin#4]
I followed your instructions to start glassfish server. But somehow i am unable to see the GUI Console. So i tried putting up the war in autodeploy. I did not test the service as i didnt understand what url to hit.
<br/>
With the API Gateway service, when i run <code>npm start</code> ,im getting npm errors.

![image](https://user-images.githubusercontent.com/13816825/30029946-4b5ddc42-9159-11e7-9780-ae37b35dc46d.png)

**Comment by sachinkariyattin** [comment]
@hiteshkumardasika 

I had missed adding the command to install api gateway `npm install -g express-gateway`. I have added the same in the wiki.

Also, once you execute the create domain command for glassfish, is it successful?

If you deploy glassfish on a different port(other than 10080), you need to make changes to _Assignment 1\apigateway\config\gateway.config_ file

**Comment by hiteshkumardasika** [comment]
@sachinkariyattin 
I thought Glassfish console shows up on port 6000. Hence I was hitting 6000(Mentioned in the documentation).But now it showed up the welcome page when I hit 10080.But now administration console doesn't come up on port 4848. I don't think I need access to admin console as I have already copied the war to autodeploy
<br/>
But i still have problem in running <code>npm start</code><br/>
I still get the same error even after installing the api-gateway. Am i doing anything wrong?

**Comment by sachinkariyattin** [comment]
If you are able to install api-gateway successfully, you should be able to start it. Even I am not sure what the problem could be.

The error in your screenshot says to install new version of node and npm. I am sure you already have it. But just make sure to check the version

**Comment by sachinkariyattin** [comment]
@hiteshkumardasika 

I just repeated my installation steps on a new system. I was able to do it successfully. However, I have made some changes to the installation steps. Please try a fresh install and let me know

**Comment by sachinkariyattin** [comment]
This wont be an issue now as  docker containers are deployed
